"""Cross-repository mock-only codec smoke. NEVER accepts a real export as a fixture."""
import argparse
import io
import json
import tempfile
import zipfile
from pathlib import Path
from body_v3 import dataset


def check(path):
    path=Path(path)
    if path.name!="body-r4-approved-test-export.zip":
        raise ValueError("only named Maven-generated test artifact allowed")
    with zipfile.ZipFile(path) as source:
        entries={name:source.read(name) for name in source.namelist()}
    # Explicitly expected fake IDs generated by ResearchManagementServiceTest.
    if set(entries)!={"manifest.json","labels.csv","samples/sample-1.json"}:
        raise ValueError("unexpected test fixture entries")
    payload=json.loads(entries["samples/sample-1.json"])
    if payload.get("subjectId")!="subject-1" or payload.get("exerciseId")!="99":
        raise ValueError("unexpected mock identity")
    manifest=json.loads(entries["manifest.json"])
    # The real exporter does NOT label production exports synthetic. This temporary
    # test-only envelope proves its payload/hash/group fields work without claiming
    # mock professional review is real. No server/database mutation occurs.
    manifest["origin"]="SYNTHETIC_ENGINEERING_ONLY"
    entries["manifest.json"]=dataset.canonical(manifest)
    out=io.BytesIO()
    with zipfile.ZipFile(out,"w") as target:
        for name,body in entries.items():target.writestr(name,body)
    with tempfile.TemporaryDirectory() as folder:
        wrapped=Path(folder)/"mock-export.zip";wrapped.write_bytes(out.getvalue())
        built=dataset.build(wrapped,engineering=True)
    if built["counts"]["samples"]!=1 or built["exclusions"] or built["rows"][0]["annotationProvenance"]["annotatorAlias"]!="annotator_1":
        raise ValueError("backend_python_codec_mismatch")
    return {"status":"PASS","origin":"SYNTHETIC_ENGINEERING_ONLY","scope":"actual Java ZIP -> Python dataset codec; not DB/clinical E2E"}


if __name__=="__main__":
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument("zip",type=Path)
    print(json.dumps(check(parser.parse_args().zip)))
